### ISSUE TITLE
Include a play again button.

### ISSUE THREAD

**Issue by vincenicoara** [UCSB-CS56-Projects/cs56-games-battleship#25]
- When the game ends, the only way the user can play another game is if they close the window and run the program again. Add a "play again" button that appears when a game finishes.
- Include a button that enables the user to play again, but allows for the re-selection of ship sizes and shapes.
- Include a button that takes the user back to the main menu.
- Do not make these appear on the game window. Make a new pop up that has all three of these buttons on it. 

**200 points**

**Comment by joesong96** [comment]
Completed this
