### ISSUE TITLE
Improve boat size and shape

### ISSUE THREAD

**Issue by vincenicoara** [ucsb-cs56-projects/cs56-games-battleship#27]
- On the window where you choose your boat sizes, create a label that shows the remaining amount of ship blocks before you reach the limit. This label must update real-time as the user is entering inputs. 
- Include some preset boat shapes that are more complicated than a line. (Make sure their size is accounted for). Make these preset boat options have an example image and include a checkbox next to it that you can click. Note: this will probably require you to change the size of the window frame.
- Write a more professional message for the case when the inputs are not of the right size.

**300 points**

**Comment by SElegans** [comment]
F16 OK (500 pts)

**Comment by SElegans** [comment]
W18 OK (500 pts)
