### ISSUE TITLE
Add background music

### ISSUE THREAD

**Issue by joe-song** [UCSB-CS56-Projects/cs56-games-battleship#36]
- Currently there are only sound effects for actions, but no background music
  - Look at the implementation of sound effects to see how to do sound playback
- The majority of this issue will probably be spent in editing and mixing the music so that it plays well. There is a large amount of public domain bit music online so those could be used as the music. They'll just have to be edited so that they will play better on CSIL.

**Suggested points: 200**

**Comment by vincenicoara** [comment]
W16 OK

**Comment by SElegans** [comment]
F16 OK (200 pts)
