### ISSUE TITLE
Multiplayer replay functionality

### ISSUE THREAD

**Issue by changreytang** [UCSB-CS56-Projects/cs56-games-battleship#37]
- Extend the replay functions in the single player to the multiplayer segment of the game
- Have an option where you can re-enter IP addresses if you want to play with someone new
  Suggested Points: 

**Point Value: 350 points**

**Comment by vincenicoara** [comment]
W16 OK

**Comment by SElegans** [comment]
F16 OK (300 pts)

**Comment by SElegans** [comment]
F16 RESOLVED
