### ISSUE TITLE
Code Refactor

### ISSUE THREAD

**Issue by SElegans** [UCSB-CS56-Projects/cs56-games-battleship#40]
Code is placed into 5 individual classes, two of these classes, BattleshipController and BattleshipGUI are large objects that do too much. Consider a way to split up these classes. Use OO principles to assist you in making these objects smaller.

**Comment by SElegans** [comment]
F16 OK (400 pts)

**Comment by EdwardGuardado** [comment]
@SElegans This should be worth a little more Steven or be split into two issues refactor controller and refactor GUI because both are a hefty amount of work especially the GUI

**Comment by SElegans** [comment]
I'd estimate a complete refactor of the GUI at 300 pts, and a complete refactor of the controller class at 200 pts.  Partial refactors and reorganization might not result in all points.

**Comment by EdwardGuardado** [comment]
Thank you my good sir

**Comment by SElegans** [comment]
F16 RESOLVED
