### ISSUE TITLE
Add volume slider to adjust volume of the game

### ISSUE THREAD

**Issue by EthanYSu** [ucsb-cs56-projects/cs56-games-battleship#63]
Add a volume slider to the game to adjust the current volume of the game, should update in real time and affect both the SFX and background music. 

Suggested points: 250

**Comment by KevinLee00** [comment]
F17 Approved for **150 Points**

**Comment by SElegans** [comment]
W18 OK (150 pts)

**Comment by SElegans** [comment]
W18 CLOSED
